# backend/core/event_dispatcher/event_dispatcher.py

from backend.logger import logger
from backend.core.storage import services

from backend.core.rules.rule_engine import RuleEngine
from backend.core.rules.context import CorrelationContext

from backend.core.rules.suspicious_process import SuspiciousProcessRule
from backend.core.rules.ssh_bruteforce import SSHBruteforceRule


class EventDispatcher:

    def __init__(self):
        self.context = CorrelationContext()

        self.rule_engine = RuleEngine(
            rules=[
                SuspiciousProcessRule(),
                SSHBruteforceRule(),
            ],
            context=self.context
        )

    def dispatch(self, event: dict):
        if not event:
            return None

        etype = event.get("type", "")
        logger.debug(f"[DISPATCH] Received event type={etype}")

        # ==================================================
        # RULE ENGINE (ALERT + EVIDENCE) 
        # ==================================================
        try:
            results = self.rule_engine.process(event)

            for result in results:
                alert = result.get("alert")
                evidence = result.get("evidence", [])

                if not alert:
                    continue

                payload = {
                    "type": "ALERT",
                    "alert": alert,
                    "evidence": evidence,
                }

                logger.info(
                    f"[DISPATCH][ALERT] Generated by rule={alert.get('rule_name')}"
                )

                services.db_writer.enqueue(payload)

        except Exception:
            logger.exception("[DISPATCH][RULE_ENGINE] Failed")

        # ==================================================
        # NORMAL EVENT ROUTING
        # ==================================================
        
        if etype == "LOG_EVENT":
            logger.debug("[DISPATCH] → Routing LOG_EVENT")
            return self._handle_log(event)

        if etype.startswith("PROCESS_"):
            logger.debug(f"[DISPATCH] → Routing PROCESS event {etype}")
            return self._handle_process(event)

        if etype.startswith("NET_") or etype.startswith("CONNECTION_"):
            logger.debug(f"[DISPATCH] → Routing NETWORK event {etype}")
            return self._handle_network(event)

        if etype == "METRIC_SNAPSHOT":
            logger.debug("[DISPATCH] → Routing METRIC_SNAPSHOT")
            return self._handle_metric(event)

        logger.debug("[DISPATCH] → Unknown event type, ignored")
        return None

    # -------------------------
    # HANDLERS
    # -------------------------

    def _handle_process(self, event):
        try:
            services.db_writer.enqueue(event)
            return event
        except Exception:
            logger.exception("[DISPATCH][PROCESS] Failed")
            return None

    def _handle_network(self, event):
        try:
            services.db_writer.enqueue(event)
            return event
        except Exception:
            logger.exception("[DISPATCH][NETWORK] Failed")
            return None

    def _handle_metric(self, event):
        try:
            services.db_writer.enqueue(event)
            return event
        except Exception:
            logger.exception("[DISPATCH][METRIC] Failed")
            return None

    def _handle_log(self, event):
        try:
            services.db_writer.enqueue(event)
            return event
        except Exception:
            logger.exception("[DISPATCH][LOG] Failed")
            return None
