# core/event_dispatcher/event_dispatcher.py
# README.md dosyasını oku

from backend.logger import logger
from backend.core.storage import services

from backend.core.rules.rule_engine import RuleEngine
from backend.core.rules.suspicious_process import SuspiciousProcessRule


class EventDispatcher:

    def __init__(self):
        self.rule_engine = RuleEngine(
            rules=[
                SuspiciousProcessRule(),
            ]
        )

    def dispatch(self, event: dict):
        if not event:
            return None

        etype = event.get("type", "")
        logger.debug(f"[DISPATCH] Received event type={etype}")

        # =========================
        # RULE ENGINE (REAL-TIME)
        # =========================
        try:
            alerts = self.rule_engine.process(event)
            for alert in alerts:
                logger.info(
                   f"[DISPATCH][ALERT] Generated by rule={alert.get('rule_name')}"
                )
                services.db_writer.enqueue(alert)
        except Exception as e:
            logger.error(f"[DISPATCH][RULE_ENGINE] Failed: {e}")

        # =========================
        # NORMAL EVENT ROUTING
        # =========================

        # PROCESS EVENTS
        if etype.startswith("PROCESS_"):
            logger.debug(f"[DISPATCH] → Routing PROCESS event {etype}")
            return self._handle_process(event)

        # NETWORK EVENTS
        if etype.startswith("NET_") or etype.startswith("CONNECTION_"):
            logger.debug(f"[DISPATCH] → Routing NETWORK event {etype}")
            return self._handle_network(event)

        # METRICS
        if etype == "METRIC_SNAPSHOT":
            logger.debug("[DISPATCH] → Routing METRIC_SNAPSHOT")
            return self._handle_metric(event)

        # UNKNOWN EVENT
        logger.debug("[DISPATCH] → Unknown event type, ignored")
        return None

    # -------------------------
    # HANDLERS
    # -------------------------

    def _handle_process(self, event):
        logger.debug("[DISPATCH][PROCESS] Enqueue process event")
        try:
            services.db_writer.enqueue(event)
            logger.debug("[DISPATCH][PROCESS] Enqueued successfully")
            return event
        except Exception as e:
            logger.error(f"[DISPATCH][PROCESS] Failed: {e}")
            return None

    def _handle_network(self, event):
        logger.debug(
            f"[DISPATCH][NETWORK] Enqueue network event: {event.get('type')}"
        )
        try:
            services.db_writer.enqueue(event)
            logger.debug("[DISPATCH][NETWORK] Enqueued successfully")
            return event
        except Exception as e:
            logger.error(f"[DISPATCH][NETWORK] Failed: {e}")
            return None

    def _handle_metric(self, event):
        logger.debug("[DISPATCH][METRIC] Enqueue metric snapshot")
        try:
            services.db_writer.enqueue(event)
            logger.info("[DISPATCH][METRIC] Enqueued successfully")
            return event
        except Exception as e:
            logger.error(f"[DISPATCH][METRIC] Failed: {e}")
            return None
